export const SET_CREATE_PRODUCT_PENDING = 'SET_CREATE_PRODUCT_PENDING';
export const SET_CREATE_PRODUCT_SUCCESS = 'SET_CREATE_PRODUCT_SUCCESS';
export const SET_CREATE_PRODUCT_ERROR = 'SET_CREATE_PRODUCT_ERROR';
